---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgCeWn7ZeqQEAkrUHoyORqeW584XXBq/tbOwx5ZGV4fhl9oZYHsBgVOd0H648J6qn4rPgZcr44N1EcpwffdV8wXleAX0DjofPyR2y3yfl+h5SNa9akzruvfgsEXyT6mkd8HL4+nLrLWjTWWzeh7WAFIRSf83bzetX1vHdI+vr6WoNsSibJyI5H//CHY6wG7cw1tkBx4zihKq5uQXeA3jZvB0UNnwnFAKF6WSwQzQSSXc7Cveq5r8P/B9g11Q8Q9kgtjf1ebPJEYZ0ow8YFJqFXTsW7mvW1FTtBRrr7UJ83hZOgOd+BoVRsSpifsesIf1s7mWkY6nakdrw8aqLVIduyz9Vk+fhE8qOGy8K9cs5bnZu/1L60srAVlnGH0ZN8+6ZxkQSLCaC/bPAlRwBTFsDhcMxoXfvGsRBsMMY4otEBNseMvy07cVECNGDU88USxR8TjngV5+wfcCNa+hTlPP6MUDZygbufjfqKtxQZjrtGVjzhBOcPbYUXhr08H9A0c3INqLFT+dIxevGudaJ0+UM44PRHlL8Ajcq1/PNodtdnNRB4ZjeC0WDU532F3NM7FPgQUqqgYeMNQj68wI/4ZEn47wUhmVm85dvsEQXTy+qDkUH+fuGHI1BvvMeAeNc4ql8iAZ34hZqdyUPxQb1lZigQVy5CRhXDmq5ZHItSQe/WLMdaMqiII2MdX6/gbWowtOqMqbbUEOkIQpz4U=
    secretkey: AgCJSyIaUbwuMif5DVFjBPq9hzWRXv/tBGxRoRpqkVv8XOb6piVDtsoSiVEm1drzK6sOC8odc5A6v2xfdQuG4aS+DfdVF5OtnNuSGrcjvQx5mQvHYQCE9Y6KABcCob5jxIepPhXQOsDC2bOEWuXYJQ0FX3CmSHit8tJveAw1m6kMHXtZyr3yT6+dwqA6ikQ+kzfmamJNGu5WQJpLYDAWPJpzLKS+Loy7rAmCAQklB95XkG5IWoXBau/FBP1JvUsT6iEndpQN9Z306aJNKyRM7zrOkGVA7VTSvO5EZ8zMi6o6cmwTxge10Bwc7A7HV6XZ1jqo1x5Vuz/QCyE9TtoaWDKCTgwT5KBspcH+ciskWL27z7ag9drloBTV8JV3gRvreYhwONQUfWv1h1Yjfn5dmFqcnJqKjFx5WxnpEQKPTWw03IGotpEcAMj8Km1kuurBTr3zu/TuaYoxZ8f6K1rAc25KgY1mAE7BZ1kXbiJbG/tSIxYW8IFkAaPxhQq04lF348+zLVCYcFAOG0pMlRE8b9nTTvojtqGfkJ2AU6FptaVaT6u7IjJI1BXLdcujh6wIvf6vgkNHtjWCh9Smh1Np9nhAMpfvDorNSgU60d+Jp6c/QhtHMyr3guSs7JdKBvEXktYxFXGPrI+a94tGAirbvKKqG4pWYPhgSkYx8gzHlVrDJqu/VNvI1eTRuY8jb6KrYBgDDwu3fNHkm1E=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
