---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgCyqOj7s3QZBVV9+6AEncSCWmtYeFzJpkyN7jTRZuU+Kgg0mDPi9xW0T9UihJ5BRGFiJP60d7ltGw6e+7t0tF8e0JVdZUVYA3wg8tJYG66gfIOElL+ojc4c3LkKE6lLKtm4xbwWNxHL/naZgakt4SX8ZhzHNLwb6eLeVTUdAs+6NeSTzoFS2yXKb3bFC7f7bDsMMDCUDx9B1WOczSd8tpBd5zjz40nkSozFUtTr/uGXXCpg9jOc1WjjAwqKD6mMX5GQT9xYnanNq+Lhc5h2IRQ4k5eLKH2KABpij6/cheOtxrwDXGoeMiBG/vUp/X6vJbiOAP7kowB1XleGj5/EVXOePUxuc13w9OkNZBrpz/Ii5yRGmt8kZwABdIRWsLnzX+HKe2+muxBgtz1eRLvnqin1HrbgDFlJqpoKS5w1vhoxgoPqiNc6XMzZAJvUbh3EKkFgVGbBDfHp4Efdet0G5e78QaSnsyUAEOBW+BVXlaq3pRFsyRu87TBwG/RJOjoAdMHtjk8MBRlnjG5aTq4FLxIKucQZTeaQHUSi8U7mWtYNoN/XeUhZAtDJ12qML2LsJYRcvPMCq38XzCjucawQi1/V7QB6g+r+zVZOLkFVTRhF4JhUOsQDNb3Wir7DHu+NdP+kzH3dsv9eZlsbK1x3f7fAh1qgJy6vJSLS91FQVqVuCLzhBn/AQ3XdtAQ254r8FiTfd3kzpQwTThk=
    secretkey: AgCbrvP3c+8C0FWO9ZYIqmo7QbV3dtHLYADOoiyvyefthmrneKqaEOJfGxmX1MPIA2cZ7RnOTL1ChtJTCGj26r17CtUES/bIx373UTQ1LWXgG7tJ66qh3xme407hdBJEJxjpeY6eMmjnoMcIZbnlCL4yPoTOTK18FrB7d/UWEb1ttHi++ccDuq6lLLYmH3FWcuvnM7DhXBTUmyCRd37YzwuRRnOGADQqQz90e0fhRJn4Si51bWnrGy4Zw89WECJBSqCMWEBvXiqCRZ7sGqtc3WyEwrfs1E6ufyeWt8Pkk4XPXF6JAvJJdw7BeEmtSFFtgt/I8aOxTsnWGa0Sxuxbad5e1Z45KprPJFwL0P2QIhXRviPxUI/HuYJ++sl6AUI4VN8S+ks0aonQmvW0NrEcvnu10qDzGrfkM1hBUt84BcEbPZPWHiWpHzLewN1fTfcT4BscJV35QmnZe0sVVuM5phXLqgIhgKZy+Ao0aSukaKz4bd+z/yNOl6Sd0JShVKabfyPXX2C/eOjyHnLMtbTY63KJdneXnZd+aGvkjL2T403dSaNUQfhJnnTRZNuucW/FmO/HWvYAlZvQjoLlFunS6JiAor+XctHWzUgq9r9F/pSMfGmm4eZiNwzceAU+VtU1XWXGW3D6dXHqjjX/+qO6sPnNSdN6OQdTvC9qLO/qmmfrbt2xXDzARy+jvDLX0K23C6HQ0F9Q4Et7gME=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
