---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgCvYXe7xufs6FxYr4kGk4tDrzco54mlTT6cbFgeZZQO1NvwrBLPJYpMTUlp/tMMCPcS4aA4+bpaFjdjag0nUmdCBy3xfw+xp4I425p6okAEHG0l+Sv1uRFNMxv44JyizSAV5v210zMyywjGD7yHTIlX7HAknZ1xEQR9EB/bYIFjMnsaIQHq/pPZ6KKm36GyM1FbWZJNxQJ1qg8VCMogjPRYsNC1STa1FEOljXwNho/y0OqkgIBxkC/9j5Dnqr6wfVLLv7icdUBaRZZAEt9VaUEzhRu1028Sp7uLm6VrPb+ZEuzJNlSRncnU6TByITXlKYY8XgzJluRPGZAsd58kJmVD/eUQM22EoDRN2vHQ1WfEOI16kfWdarFonsdvWlf0D9Ddfx8k3HVpIPIEmWr2Eflgclycu9gnCrW4vWodpQFzU23a9glZU2Osh6yQBHDX4AJpIHnzJFkViCSuRcfOWHfvlAoVJ/Wsb1nl8VQ1W6DUa5RSRb1audIp1LxFeYgH5+dYW0gKcMPJ9ZzhJGIxrKLIz2xcibNiZIFo7QGKCU5SK6vDPVjyLJYTOfUcR+j24IOigqkVCI7klgh1035ND35kh7wYWmy4NnFGM3M7srq1TO/s0L9YfVsd4xZdrrIOZR8eeIFppaVYcJJ/qmQC+txjYYCCCfyyf3EgxtqF0BPaXTGDCKvS5gk+L5zoVips0DWRkCY0qf//Tdw=
    secretkey: AgBHpJM2gEEb2ByGDxNImYXChNEIxRlg1vXb+qfy/IcT25ssXnenbaOa3+AoSAwe5EwNXis4QkNEub7Es5ZIsjsrD47adw/d7ECAtWgtMouL3fSpHwAbaxn9FP2pA9R2mq6+XcuteYBF26g+49JEtRaZg5tPnw0LW7e/4C+CBQK57bN+AQMllWzRVYT2quy3ewetFNnNZXlN5mG5LCdkH98yOi75tjkz7xPFOCuAw5tXiAn4mYgxqSVfSajLCAbfsPyKFJu0SStXuntXlQEHfFXbSDAg5a/ayQVOwwBHKf4BO0gdL5bQN6AZev4w/zaTS7R0O0iYrH8wDKY03HC2Gu57gLv2HVugs2qg+dhkyVOWRamjcy3HnGM5UCxnD/k+b7nK7l37HoFvLefEm7n5C/bMAIzke5QQJcL6BSyxFRc7+9KHAlVi5Lty38fQbZp5ghiMr2aEKVO+2talxXcr+fnzuDFXwSDYlQ7zgkusJaq13DPcFrMnzUvLYbrdVjz6UGuq2yImzOX3jeFXfLCCZO2XdGTS/axYE92LML3qhLagfQbuHc+46TLJaomklte7I9Rqprjs6OUlD2+w39bY5HcY7GgMuXnUrwMMBILC8RduQK/RDPg/FopcO2wkgndBPCDsSAmUcGMCRT6yLGmggR7arZQkPWx5yJk1hEXJf7Ar86bNFLv49kGVxEBBlNslwvc/YKRbFuqoJa8=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
