---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-gateway-auth
  namespace: loki
spec:
  encryptedData:
    .htpasswd: AgBF4zmiJAmh72YED+25qPc4k6sWAsgrDaV+Vot/6rhmYkXP093L9rX1iGpKx6C/gybqBsgO2b8D8aDW41ttUNJ0xqemtEBZTXAR4JJlZsqg4SNolCsh0ikLqv7yevb0Sa3TxDqIXJd11whelMMJiYr6T15bU8attSsq/SVUovHnRVKLFLXVwyNZvP0mP+NVAimkhHoMp/39gxfOxNQu6y1MmT6yYn302WuTnOba5RGADShRU2e2JdRIMhelOAXaEEVLSn2MNzfXsHyQRx0ZkzfsbeAoXgfh1ZuYixFO3nS1JTdPU7/UySMaW429XI2kVn2ZOe8Ff+gnAjN2CBiK1wV8j1PZtRJ9HNUNVt3ePZfkUhjC5pO9D7XMYYXeNGNs+GCVOP7nnZqd+4veAdU+vSIGYH9az+GX2T4/dr3KP/jNw/gH1rRjJsjDrDiXZVXwsO9JrIap+owKz5HLhIm0cw4ITo/MNN8nX4DYxHEBo2uJVJXnX+i20Y6cOrAvYwCcCnvim+VtbLv2Bgu4MNAqF0g1o8hxuAlEtorbVIfVCPf/qNlfHGjNK+7KUe3yaD40RpCnXdBzY684WZOb8KbhDhsmRMnMs4PpP4/9zQkdR3YQ9YwN9Oq+iBE+o4D4PSDQXYK8eME25bb/4VxCvAGzaUSA/J/ENHM7VzddTzs94A/g/0aA55lUYdVXZ7TXLKPzwMMPvYM4P2KjVAamCkhYDsoz+IVVwP0rSlGZZEJG2tSXunA5NDU23wQ6TR0m+cNHpt4gHXg=
  template:
    metadata:
      creationTimestamp: null
      name: loki-gateway-auth
      namespace: loki
