nameOverride: redis
fullnameOverride: redis

global:
  storageClass: standard
  defaultStorageClass: standard

auth:
  enabled: true
  existingSecret: redis-password
  existingSecretPasswordKey: redis_password

master:
  persistence:
    enabled: true

replica:
  persistence:
    enabled: true
