---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCxViY/Pynt+AcPRLzeE9NdsVjZpeJCGaF01sCyZLR2mm8IPG97Z+qFUx84szvJ0MeIWFgt79Entp9jNTXVHwGL0BUPhUFSi1NHeajeNp60VQMO/QkT/clrnRh7411AnD2fyl3vpFoPH266KzIXswObRfJdZP9phQOAr0VsJVjZ9OHXuvUoI/YGuOvXSF9YUVOIs+zxidMkPX4N/lSPkPB93yM8w/H1uZcM/kqh9YgOkEiCu/ZphO2TTBg3v13PzlDe92wPSmUoFvEKdHrQjuh33oGXjgMxsElCOyVPIrPCXZRsML+SHMuUqW47edt/oT9kZv8ZGx8hs4x+mRtjValHRZt7gKPZhg643roQ5Ip9ms4ryvZoaB8p0DGAJ5wFYG9w1OgxuawPQIEORLKIKhsAwdsX+es3n08C5o98L+NVErT4PvVggZM+MChzv/G+4N386PkQRFsMFSlr7A4FPdGEU+/upSjhMz93WT5v/dLHrHceZYE1dRsK1tHHEw173Yb8I5WgN5Jar2nKN/+JPTWeN/wgQUe0E7mVOIsYwH+SdKW4UaDneHCUDZTysmFZxo4z6ZTZQOCZfBDRkuZ0elTCECl1cGNw5j9sXheA+ySIHge5RhjdfanSP8DSU6E1aCuc2ZDHIMzVdQUk2FcnWj/ZdJ5/nrlvGV+QeP3LXoqEstlFr1OTnLbzT8kDmLVSArzbioQZdn66clxT5WWMNk+AZULe72Mj7i9r6sqTbQR7vHC7LreoMGBtJIStLOYezuYKm1G8hNM6/Fsd5Re3pkXTeVyOcZyxgIFGRRMD+7IvXKbhecZOwmCrqTBLKPt+hBd4RuIjhrQDRIpJtDHlIR+IBBin
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
