---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgAguHJ5p+WbxbqaAIyKlECyDMQzfQ/V0B4KBzIjctUdrG8H78YJBUj4vUPdaxWvjh5QR+g3yZZwwRTDazIrK4jF8XpR0WT9GzYld7zjxZ1bpzcuSZxVqjiglkOODIzY7FQFu5Aq7dTLkGm+zouGWCcE2+qH494UPsOevJ2uhlQnODsmBjJlaZL9Yl9d6Q+TGcPwaUNZCOX//cHCTHoyjPOAL3URa22riF/STE90I3ZITW73vaoGtPHcI6y5XaqeSIqj4CNSMylTfgikl5TFq7ECk/n26GBGBOAIUdMg6b4ZCi0MnqWgIejBbsY+yEpFxCcaoShxJK0ej+8/XGVYMEPommrStutX/2bsyZ/sdUer6TZ5LgqNzwAEdXIzU49Qdlu1YtQR97hkSGG/Ll73MQtqkXEYPdfv2iD+vgKPHj813izy7kiXunWqhUcYzWYt5vjmqwlaboN4xX+o894CGZgklxSSjDpfDOkv8bXp7WXl2mlAlZji/zrZ/DrajaQq3fHcXutwBLcjxeG+fPEAJ4TZTm378lHysoFjUs80PGj3/2LN01PcGO3PevhdUl0M5OL+zju7hUMUEFa+MpGOISTM5tj5cA7+mHaJL8LoxvTzLmsFIxLsXQNUwtzn6vCil8MMiRJjoXVkp4gAFcFIcAd8Rib4lEhd/LlkRcSK24n0Rjfm33ZlO22V44HXVIr1ek71OI5SP9gH/nAt
    root-user: AgBx0rBnkWMo8VXvR65gr8BOczu4Qh8w3M5kRb/rzaBhanrVbA60cQo+uILk75P7zXDUEjZ5J2k4AqD4l3kYK3EgLG9q9Q2yAwjos+krz3imRRb3N0Ed4JjM+OMVxssXJ5IyLGlzsyYDgPbThSqX7PSQAERy9jjqDZn6ywuYx4xw+VvF61Yh+cCdynu+arZePhGV9qb+E0Dhmp0VJpwc9okFj/FXuMcbH3hwsbX4QOzLe7megxA1MD4XxM71BQ36kK6pcOOmPQL6Zc6bYjulJJvg8paXYaI5oTRXntsWjCvdR6bAATwnOpA7LWQZK7mzololyr6FwzLG6o0H5RkJY/jrdKuZ0c3RiA3wuzE15IwCkko18v3i+1KqDT/tVWxuJB+eQS4M8c274pTKLJOgwBDAK5QJ7wvV9y5AokloAxvFnbB0wJO2q31MfEAHyu+foB2gxGa2JerMmwitJtUa1qmNn+5hEIazA4Nkd5ZtZMovmDko30TAF3cSgigq21BvcGXNLgJKqC5vCK5mtdi8WPCxSyo6q7mkIgXK2ln/xziuF9QKbb3Usi2CwIdqr/pWDug7bHGoWY75Ar+dlRTyNjDhnVbNnbpRWj7LdB8nipQl+iZ0lBuEG9RTnDx6nFyJiiV+anCP+1/yTNqBcASWGC3ob06bn1wtt5cak3Se6bNPQpAoA9suyiU2V3a1sfYSoBMJH97R8cifXvyi
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
