---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgA6QeQHfcBlHbRXXx3ZxBXzzVayjFHVRpNkCkZyEs2TSh5Z9VDSouX4VTxs2jL++QlAB6q8MJnYVDImbW9BZ+BSeTzPURy6ZkI4vPh/asUPHjMJLmZWZEMw9tXhFQ73BPsFDOO2TS1iRFaI/2R7X8ZxvdEhbrNdeenpyej2TB/6s9uROAp49TyecWoqrju01MhwAgDqJhxpv9vvL6WbzWBfHx3ywL1Ed2fCwemA0G6HEn71hUcrtITv5hq7SNermubDVE+P7zLTGX24Brf2bpvUdmBQ34XlORinJMW4SaGaWJcu6ZYRaRI1TSyDm0z25h/hPS2cjKhqBk8K5r5FDL/pgObIXKBawvHtykX1tZb/uEdsC8IxPxGtwB1eGv6KU+V3ZHgBaqqD2HpniDA+LYbDoLUnJu8Zleo6dlXERuhhphjbWkKXO3XBqpfv1aXFh1mAiZ6c6vE+5kf+Gpdt027TWl6e1HLKAyhRWDVdGLKcOZ6tREBpl5t0AzrsfgajA9E3iXBr4IOe/jk5IGItAgCNd9+Ou734NUUpbNR5bg6FX68IXxwFIgzbl+7cP2Pv2hPxYgoOWvSqC9mV4mFmVgyCZHa1jMy50gtDDj/CYxZp2Zv4tO8KMZysezAUnhufqexWlG7Xhpdf0y9EJDqcaDEe3VD3gRTu0kZ/RNtXI85kh6lFVduFmZLYPaum3/EW8wiGP5NhKZ9aJnFrjrgbxOqMM2DFbruxT4Tz1QW9o+m5moROaLIWgvILK2CWQ0SLDZKmczbzHIY3gx2CCWKeQyB0EPvCjMVdH9EiaQFvCLYwxhcyuYORp+xGeJWVvLqd16ZV1mUW0broB/IzY6G8T9kTbxGH
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
