---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgBw/e0T+8AygQzw2ZgAmehf6GFYqGH8CRK3buQFzTYMXJrC5JJ5mLFRpzN+iy6eOUuW3CufmxmW5ymFn4IS6KLmvR8sRHrt681hYRBJxXEV7WKtcT5pZR6WxroK/lFWq64zeFKNZcIn+37wYF6gKzGQDioGmm49IcqjBLodIzBzbZve3LCAeIpEsCdMswflKlzOKaSmlGeBF5xOs3vhQlQQybufq7OEi7dD/wdglp/HSF0snma/VgtLniOUKFxwlDpxww1ApIi4I0JlErJSc7rUpb8ZL39rEySfsxRIfWZNajSQ9761PxBnRoQVt83+2kMocl6yusCleIQSD5j2UCXw+nJjUrNFu6sO8d4dviqyj8qcz1NaEaNGEoviryLjebSmXEg+hpwPFWPkZf80ehkM3E5SPFj8MjMGWNXF2+aCLw0ixiWvlYMqLJm3RijWd1K1FiKYrI9cIZ5GIxTXZBly4mNHXG2mKleFA/RHv6yJMt1WYN2/BJb9X/xEkp1ySR4lABsursjE6cm/58f01b+gAFE/QtaD3FgGQPwqdSYJGwU/nNSbhx26t6SD26GEdQaDhE23dnUtcY7XIM7j7M64wnE57fACOnskfE4LVIeFFY+EX0ybvyrfntCO6WxQYffmDT3RcDyxOKtxR77sOO0RNkkPQjw7RiU0Of1h89T8Uc4vFlYfoD5PJAK9i09SWyJJOWTXRGeTX+zA3co0po6o/HYnud9RKSXpvBubqWNJmYx0ywf8suv2p/vD2Xxtev4ImWbPLQHN6ntePxvWTSlecJN0KiwVLSEe8sLPC8mUWy7LTixqNsC88Q55cPs16nxUk+MiZ3AKWKK+sVIbTgZi7fmG
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
