---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBRDZiJtIu5P4w2mK1qsJv5rGCB1H9NKzGfBgyO7h+VMQzrTFlaoVCXljyoH1PCztCGm34h/uXYL+OVQluZTQUITYS6DpueBukbd40xyZE7qqiaXFvkx1V2X+DbATAJ9oo+0f5e1TDe4GyXqvYSx4fIG1NAixDKDa686l28w+Qz4VsLoPY33Ch1TCxASqPtz/XryCAHWzPgg3QJaS4JcO9iOcVzTR8Jvrx/765eKiF23AZKcjp63wc07bdO8K5qjN/RSvoJXLkpdMUFvp+Hpj54XuZQSR3sEMvvvUs0OrVnDh7xeCiJO1VS8sEDiosaoOB9v9JIZ8mVgGZlRArlJEK2hIBqA4Kpdpfx4TXouQ6rjDCZ4O5oy7YzOXxIoSUVS49BQp6WnubA1i9Tatoi93YDs3BEnr8X9nIw8vxoYh/KlSgTNmTnBsjLtavTouAUH3p1yjSxz1E4rrzqcq4Ubfm0r4AV1vPArp4IWFoqUe3WVgyj0gz5qT0aZWzghbA+IDbblbznsB+9o9hxiNB/3/EQOVjNiPob7imAARdelBX+Bh8KQ8sKMORsaJLJPXIT2GstOT4nYQpD47wOvdFHIe5iZEwWoSRhAPv+mlekfHzg6V4K6puFFrzzy8ckcvX0jyFDEI5VctlebEq5OdW7mRUOrXbRcHy6s6n2RxcT+pg0NVMxM03ONhWYKtg5O1ztI1+QTD8BX6gpqGP/
    root-user: AgB3h9xjJINzTZKmsXLFw9JAgFyOcqt5hKD0yrk5IzXmDns1FS7RXBYccshGBAyoGsmbovy8BTKhgxYom+KUUC6rHqZe+K5TTWEP8is0Uw/6pgcyzgWTuGdKOuf1elrikBSdeg54UhZfWOh5hznWMiv2VSrJW34GV2oNA/fcdBWfb4xvTiZB/2tVVyalIXgRQUV2oGvTOYoOE+saLEGs9dzNetn2SXVd2hdyEJ9WdZMSN8C5bhubMgbPXMEXp7p1NHGDZeVBY9GKkMIhIsMNQ04W+M9VfnrJ98hHLbGG207XfNI4ztBuTK8pRQTTzb+df1YDlXpgzkoPtRV23Zk2tjpXQkbLohWlXUo05CYtd9dIeyKEO01q7D3mv167b+xD1967bgiNy1WdsqP9kp1PPs31FzfnhJvG+De5Xx/3rBkObYZshOXARgjwrQvgeeZxQ0FL/5jn+bkIDxM0EiTFqfa2MqVtxVbuUmvGKp4+JPR2y02GbNCxOnA3/ph2kgWsWerkfbOX6D0OAPxg72e7QVFK9VICkHZ5+a1RThp7e2Ci/z/HPlxjNDJjsE44i2AlaiiEgdfoLLQa0AqGAE6GIzwJIGI61GM2/gQv5bMO6LoqvO9zSmrOBoTXSiWrlyRd0WN4ndmnS4ZtX1NktY7uyQFnvOXR+DpgACP0Q+Msj0ntItP+OYu5lVwwhB9wWg5pV4M0NsINHekJXEym
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
