global:
  extraEnv: []

fullnameOverride: grafana-tempo
traces:
  jaeger:
    grpc:
      enabled: true
    thriftBinary:
      enabled: true
    thriftCompact:
      enabled: true
    thriftHttp:
      enabled: true
  zipkin:
    enabled: true
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
  opencensus:
    enabled: true
tempo:
  structuredConfig:
      memberlist:
        cluster_label: grafana-tempo
        cluster_label_verification_disabled: false
metricsGenerator:
  enabled: true
  config:
    local_blocks:
      filter_server_spans: false
    registry:
      collection_interval: 15s
      external_labels: {}
      stale_duration: 15m
    storage:
      wal:
      remote_write_flush_deadline: 1m
      remote_write_add_org_id_header: false
      remote_write:
        - url: "http://prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
          send_exemplars: true
