global:
  extraEnv: []

fullnameOverride: grafana-tempo
traces:
  jaeger:
    grpc:
      enabled: true
    thriftBinary:
      enabled: true
    thriftCompact:
      enabled: true
    thriftHttp:
      enabled: true
  zipkin:
    enabled: true
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
  opencensus:
    enabled: true
tempo:
  structuredConfig:
      memberlist:
        cluster_label: grafana-tempo
        cluster_label_verification_disabled: false
metricsGenerator:
  enabled: true
  config:
    local_blocks:
      filter_server_spans: false
    storage:
      remote_write:
        - url: "http://prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
