apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.6
  template:
    metadata:
      name: '{{cluster}}-argo-cd'
    spec:
      project: cicd
      destination:
        namespace: argocd
        server: '{{url}}'
      sources:
        - repoURL: https://argoproj.github.io/argo-helm
          chart: argo-cd
          targetRevision: 7.*.*
          helm:
            releaseName: argocd
            valueFiles:
              - $values/values/{{cluster}}/argo-cd/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
        - repoURL: git@github.com:devops-toys/devops-app.git
          path: manifests/{{cluster}}/argo-cd
          targetRevision: '{{revision}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true
