apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.6
  template:
    metadata:
      name: '{{cluster}}-argo-events'
    spec:
      project: core
      destination:
        namespace: argo-events
        server: '{{url}}'
      sources:
        - repoURL: https://argoproj.github.io/argo-helm
          chart: argo-events
          targetRevision: 2.*.*
          helm:
            releaseName: argo-events
            valueFiles:
              - $values/values/{{cluster}}/argo-events/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
        - repoURL: git@github.com:devops-toys/devops-app.git
          path: manifests/{{cluster}}/argo-events
          targetRevision: '{{revision}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
