apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        repository: https://github.com/tomasz-wostal-eu/devops-app.git
        revision: dev
  template:
    metadata:
      name: '{{cluster}}-external-dns'
    spec:
      project: core
      destination:
        namespace: external-dns
        server: '{{url}}'
      sources:
        - repoURL: https://kubernetes-sigs.github.io/external-dns/
          path: kubernetes-sigs
          targetRevision: 1.*.*
          chart: external-dns
          helm:
            releaseName: external-dns
            valueFiles:
              - $values/values/{{cluster}}/external-dns/values.yaml
        - repoURL: '{{repository}}'
          targetRevision: '{{revision}}'
          ref: values
        - repoURL: '{{repository}}'
          path: manifests/{{cluster}}/external-dns
          targetRevision: '{{revision}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true
