apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.35
  template:
    metadata:
      name: '{{cluster}}-external-secrets'
    spec:
      project: core
      destination:
        namespace: external-secrets
        server: '{{url}}'
      sources:
        - repoURL: https://charts.external-secrets.io
          targetRevision: 0.*.*
          chart: external-secrets
          helm:
            releaseName: external-secrets
            valueFiles:
              - $values/values/{{cluster}}/external-secrets/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
        - repoURL: git@github.com:devops-toys/devops-app.git
          path: manifests/{{cluster}}/external-secrets
          targetRevision: '{{revision}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true

