apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.6
  template:
    metadata:
      name: '{{cluster}}-grafana-loki'
    spec:
      project: monitoring
      destination:
        namespace: loki
        server: '{{url}}'
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          targetRevision: 6.*.*
          chart: loki
          helm:
            releaseName: grafana-loki
            valueFiles:
              - $values/values/{{cluster}}/grafana-loki/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
        - repoURL: git@github.com:devops-toys/devops-app.git
          path: manifests/{{cluster}}/grafana-loki
          targetRevision: '{{revision}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true

