apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jaeger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.6
  template:
    metadata:
      name: '{{cluster}}-jaeger'
    spec:
      project: core
      destination:
        namespace: jaeger
        server: '{{url}}'
      sources:
        - repoURL: https://jaegertracing.github.io/helm-charts
          targetRevision: 0.*.*
          chart: jaeger
          helm:
            releaseName: jaeger
            valueFiles:
              - $values/values/{{cluster}}/jaeger/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true

