apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: dev
        repository: https://github.com/tomasz-wostal-eu/devops-app.git
  template:
    metadata:
      name: '{{cluster}}-longhorn'
    spec:
      project: core
      destination:
        namespace: longhorn-system
        server: '{{url}}'
      sources:
        - repoURL: https://charts.longhorn.io
          path: longhorn
          chart: longhorn
          targetRevision: 1.*.*
          helm:
            releaseName: longhorn
            # valueFiles:
            #   - $values/values/{{cluster}}/longhorn/values.yaml
        - repoURL: '{{repository}}'
          targetRevision: '{{revision}}'
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true

