apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.6
  template:
    metadata:
      name: '{{cluster}}-minio'
    spec:
      project: core
      destination:
        namespace: minio
        server: '{{url}}'
      sources:
        - repoURL: 'registry-1.docker.io/bitnamicharts'
          targetRevision: 12.*.*
          chart: minio
          helm:
            releaseName: minio
            valueFiles:
              - $values/values/{{cluster}}/minio/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
        - repoURL: git@github.com:devops-toys/devops-app.git
          path: manifests/{{cluster}}/minio
          targetRevision: '{{revision}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true
