apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        repository: https://github.com/tomasz-wostal-eu/devops-app.git
        revision: dev
  template:
    metadata:
      name: '{{cluster}}-redis'
    spec:
      project: core
      destination:
        namespace: redis
        server: '{{url}}'
      sources:
        - repoURL: registry-1.docker.io/bitnamicharts
          path: redis
          targetRevision: 20.*.*
          chart: redis
          helm:
            releaseName: redis
            valueFiles:
              - $values/values/{{cluster}}/redis/values.yaml
        - repoURL: '{{repository}}'
          targetRevision: '{{revision}}'
          ref: values
        - repoURL: '{{repository}}'
          path: manifests/{{cluster}}/redis
          targetRevision: '{{revision}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true

