apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.6
  template:
    metadata:
      name: '{{cluster}}-trust-manager'
    spec:
      project: cicd
      destination:
        namespace: trust-manager
        server: '{{url}}'
      sources:
        - repoURL: https://charts.jetstack.io
          chart: trust-manager
          targetRevision: v0.*.*
          helm:
            releaseName: trust-manager
            valueFiles:
              - $values/values/{{cluster}}/trust-manager/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true

