apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: universal-crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.6
  template:
    metadata:
      name: '{{cluster}}-universal-crossplane'
    spec:
      project: core
      destination:
        namespace: crossplane-system
        server: '{{url}}'
      sources:
        - repoURL: https://bitnami-labs.github.io/sealed-secrets
          path: ''
          chart: universal-crossplane
          targetRevision: '*-0'
          helm:
            releaseName: universal-crossplane
            valueFiles:
              - $values/values/{{cluster}}/universal-crossplane/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
        - repoURL: git@github.com:devops-toys/devops-app.git
          path: manifests/{{cluster}}/universal-crossplane
          targetRevision: '{{revision}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true

