---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgAWdwDfA8+i8vHApfnciS0k5/31OmeHqbCJR68YxgTZOKvjiB5lkEhsjyEITJ0UUxQSB1jMx6sKqgha9/oPrR50oRrEp7IdbF1zR5n4PVmKIIWU/+QLpacP7T4cX5KqjfEMK3/+aPeH1NktsRhp7ghua1eaj8B4HdVM8R3CB/oZo6YgwIN7AOUtfP8tZqC/PeOpuL1z/MaIrD9ExvUqypt4ujeUroTtOoOAm7HL1vqUVR40/paHXiVVPeTwvSrGgQclEqAq3NBbRjZ090IoyfnF/vWz2U4A1Ha2pD7+uowYrSgvITpURbjGwqsvXgBlHWVICzDWDSlMRo1ZbVoT6K22Cl8yLRUDlULgpHoW9eSA7R5UfcZ290ef6xVMQXpIpqXU25hMBPw0c79Mx5WXln0cQ7nJ+gN/MhA/sDKvp/qbLJGIioeTUzRPZRsZW9jpDLNfuq3lQICgtYvIgj/Q/JF8+stwUdrU4NRmqhuGYGOrSsN7zQLuJT2Zjjvk6J+TqvcH1NzEc/8KaomvDxbEHJoy2TipBsnImKN7w6tsfqah15MncaEMhgSJDgNNGM7+tUcB0PYqABcan0f608usriyiH0B2nZlhPa8YbNuBM9LInJdne0QezH/1NJFzJ75c7WL9cQ7BleRANrWUEgut39vhy0jXKTkLmXE7CzMqnhHpc/uM83/226Iv/Bbdmwv4I8sIVIM31Du4hIY=
    secretkey: AgBJfdK/RQh7Q1K7HuVgPr+zdxy7APzrLL7QJcXSR1MciZBcb8ALIBHGhygs0tqzAlqwaJfOrL8GOg0+yXwZtefxAfTUBZ9HdLtKPB6uX2xOH2HDTs1q8LF+AVXdw0YpRFBo4ohaQFiyP0X7jXgbUcnsTyLH8tNHN0+DbLHtjureXUs8yWWCC4gR/XW4/2Tzn/qCpIyJRzavcpcjBfeXbkUxS1bozLqjc86sBx/mm8HY15pj69RbZtMoHmBFe1MqKhqujIezPIeaHReshWIBVV9d9NEFM/Mml/OOS5aBtJ+NC8k+7W20CE/C6VEoOmOIR2UOhh2rG0mwlWAhH5NKhHasl87t2tGILXIgFPXqM1dRjDxhroHcJSsTwjYbr1/oeK3k83bES0YihUE/m6lv6oLllkklAN6lOvUvfRjQGOoOEdZpym4nBsCDyhFB2X4n4JoysbeEMvo6ICIFUaZfgXNyLjKxWAWRX/wqVM1d3j0BwL4xNLRImUukXJfh+tjFhQvtbrz799E64UOh1piAuLG6w+t1ctOpXFrubG36xc9eJcW8LbnE9q+Y58v9T8GkAUwV57jYmsVoV7VFnk8r+2HrrsOzsmAskVWlNCDfXGzxGlnj1c93ugbh4NCsdY0gqmbkgNvaSSP6xnD4zcftmL0VwCz7Sf0+PWiCtm5i0shpFEu88kZdU9V8/HQx8qt9nC9K9uknt9UTybg=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
