---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgA8RUMYGgddi139pEJRXDYaH2CkK7z8OHMxFrw8D9btDv45wvYkxKZM+2TaF/5fmZl62X5aFBlzUEm2OOtj17Ww5TwRTlqqLFVklCBVYSW2Et8xyx/1LwLYIw4SQ63zD3BiXu0fOc/bsmKsn72+eeLZRAIsn9l1A/U6U0RYJBwl0VZpZPBpfAd/rp8D81CBUh4tVPZQaUaZ7cKJjZ1DI0YvVo+h1Xj/DV/gvcoT9/rfTYm19Nk7tAi/7yYqdclJvCWTzHAS/2GMkMqX78LRgsMn4pANjbmtBl86ZZ0QuKtCtUF8di3Whs9NS905zV1p/MYOtSg4VqJoTJ7cXnAmsGAHeVnZAC1a7QPMj5RgrwBGRYycNvShMDn7ijJEfJ5KHxXfQ1bb1DlKJhk5vYJIXUVsd6h0W8tjufdsMlB1FNbYL//mP9mJeTix8ZrlQDP8iHVjivjZTp9zeDO1QLeUK3Ar4mRPFtJm0C1Iq0L90Of5LE/+byXsl6M3V9ymwLeiKqrLnY0sY2t8psuvT3CNIpOWYYplDi6fJjZw0T6yyTzAy2I6JlaqdtBq6B2/EBW7ZOZbLIkapzXg4w0ZyPLK/lfg+n1omrAHBO0WePmRgA7B00YvWFXM5hxt2UX8C7bebJ22ZrFgzgx/eAOqZwDY4lL+7RL071Ar8ceaMd1h2mg6Rs5Hw8x7mzvre40SmxJSN4m7/n0YYh9ECuE=
    secretkey: AgC/ijaltqxREknix2bUe38NNaHbO/Z9+cjW8rzpeL9QmVUjegK9nXNHKGQgAOAESGX0YEGqcuYcDbCWteWuzNrPx9+ucX8n1uPgQ3i+ckFXfxiIiBjTuH78goCM3Zsezuv6i2zjPIynHvYtt36FrtaSM2dwbHaDdJLJeoZzBUzaOPSLTNYUn3o7vdtvSfFgSkSzrUSHcaqfP3V1JZIvKZW5OYvOT4ZlO2u6Q71/4+ZYHlalui23oeGCWDjPEYvN4M/EQPHIL5xrq0r7DJebS2YZljuTXbHuXmZibuFHxeq8oC3u+WEyeaS93qqKnWNvCUpP9sJJDhCtBHL62pDg3qxtBl/Xvf+e43+nLCcwsTAvYWVCVSEKrUhxEog/kTVAB5CpHbCAynrV4sKzxjnPtCvnpdwMoDGR6s493NI+TqhiABzQLQAfZ5w+isXHIzZLalM5FzqlXcTbKFrkrGb3PgqHMihl1nWk0uPxQSlIqA0YEmcmrsbpk5BMJwc6yZ16GicS6nWfoFxW+GSEou2n910sSvrc6NezZaoJyRyyz2bLtWhT43jJ3M+lFYy6p90WfddJsWaCccLayMI0UO2jJZomcYAPTGy2lnPczpiYeGV/P/hbBav7mUlPRrHJXyGRkoR+Sb5qww7LV9fA4gWj0d8ul0FPrGZDUEPEONsl7pNaKIPI+IAJeS7pZ+t+Z1QlCs2A1ZNk72MOxg4=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
