---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgBzOA8t+PEEmL2iTfQMMTXAVRQuWH2heQabm2oyR6s79pz08r7hEZezjZ7O0a6ik8dOtwQXRT1RDP03+rQi+KvnqCBy4UfQCjj9jP2c55Di3n87DPhmGn1Ks4hn9frB55EG4IOzEYT7smReR3cGI+kPYxiacvo6SwVJGNrom96PR4UXbIQwAgZxXrJ/HY45pw9dnHQ2Osy0Pmnw3zKrcZka5UGbP9XWamKkKPjaFonzrUY8tpfl8A87UV9gaXcS55i6nkmFxGhOwjFZ56CM4hBtaBlAkIB3x6LGXn+v7YvHbIyfgHaMtmHBk5AVndiuoJftlLmgSrb4UzBjWp2gGEX9yEDZFmCtI+Ak2ClTQAchlpnPHg7N/d9pWYow+R8JkWeHxa3iM0ZrXehY6y8rzJtpT4/WBKUL2fDegZa6ucCH1lqoD2UAxgr9EhgoYvqFnjyEo9+f+/flEA9qUONlzls62hPwedjVys3zkGYBeoRLIXFDYuoPBjli2tbcvLlIyHxyraTr//RHQoQISt+Sod3RvGXzgskhBujKcaCnGNkL0Y6/mqHZ3b60WoH1BNMvHh6Atiq0R88RLi4x8dWLPnNiNRJO0mYRqw/yFO0uGYE0fAlb39n3E6TUpW7L+GCf+yfeOzHCHOQljfaMdBpTq4LdDrmSSiJxkBCqx3GWwbxR5Y0RR/05sIXKq3w/SxYk2FKBz+WokoxSAag=
    secretkey: AgASQ40/dYIbGOYrEdRqu3P8U3hOtoPnV/mDCOpBDuGuYfX2y02cb9uJ+bG6Ta/BimxUWKM+ebxALfPSHXB4nTgPKsqF89c08wW0Qlp/IUSQ2zn1xpb6cmE55zgDwwyl35NSwrpS3dcgJzJ6GtEfWSYIJpdiecYssKZK+4HG2+V4j506aglam+h73+FApUDxR/wP9zKCmv8w41uY91VJYx9ONT/ovVF4yX+Z7aD9GIKUSDoFLTIVX2AqKjqxhO5AemE/xR6YS3o/1rqFQ012Yd3MNlTAcng9QyhADDk0RS9B418vBzKxOoQAvU8gZLCgvU1TTk1TB30ZErAmxrdlK8rnpJmGxZdguYOJAFglqtPN34eLc7NH5z/LnLpL3C9ajKPi5NFiAmcyCAFOUp1bbtYZ051mP0Y91Lkxwh+vUT8ipxtLIWmD66vDP1L0TG7F1ETQ7VDteTd4lYRWbuQK0rCrpT6EUt0TzOIC0EkpTujZ3xITqIJiUDidxvnFxOQZ1PlodL5gShqGa2q+BROy6HMmM/yEdd395OjbkAQcyMfzbQHVkaYVHQjHoq2bzKltypoaf9rRS6VHVR/E5FNUX+B3jYgi8ylV9IVSNzM+ILSOLWnIrVkXzwlqvQ3CkB5OoZTTeZWr3lcXo9dquhCOEpwQsS+eBYnC+FNmUWw+x1n60+9qnDEH8o3avRgghnsM3Y3kUOscb3/3bmE=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
