apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-devops-app-release
spec:
  serviceAccountName: workflow
  podGC:
    strategy: OnWorkflowCompletion
    deleteDelayDuration: 30m
  volumes:
    - name: git-credentials
      secret:
        secretName: git-credentials
  entrypoint: main
  parameters:
    - name: pr_number
      value: '1'
    - name: pr_title
      value: 'title'
    - name: pr_url
      value: 'url'
    - name: pr_user
      value: 'user'
    - name: sha 
      value: 'sha'
    - name: short_sha
      value: 'short_sha'
    - name: branch
      value: 'branch'
    - name: target_branch 
      value: 'target_branch'
    - name: app_repo
      value: 'repo'
    - name: organization
      value: 'organization'
    - name: github_user_email
      value: 'tomasz@wostal.eu'
    - name: github_user_name
      value: 'tomasz@wostal.eu'
  templates:
    - name: main
      dag:
        tasks:
          - name: notify-start
            templateRef:
              name: notify
              template: main
            arguments:
              parameters:
                - name: state
                  value: pending
          - name: git-checkout
            templateRef:
              name: git-checkout
              template: git-checkout
          # - name: determine-version
          #   templateRef:
          #     name: determine-version
          #     template: determine-version
          - name: create-prelease
            templateRef:
              name: create-prelease
              template: create-prelease
            arguments:
              artifacts:
                - name: git_repo
                  from: "{{tasks.git-checkout.outputs.artifacts.git_repo}}"
            depends: git-checkout

