apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-dt-dev-pc-001
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  data:
  - secretKey: cloudflare_api_key
    remoteRef:
      key: cloudflare-api-key
  - secretKey: email
    remoteRef:
      key: cloudflare-email
