domainFilters:
  - "devopslaboratory.org"
provider:
  name: cloudflare
policy: sync
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: cloudflare_api_key
