apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pgsql-argo-workflows-daily
  namespace: argo
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: pgsql-argo-workflows