---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgAC/GrcIh0MA+aLLwzHushqrZIHsMAsbgEJdyX63+vXlFyN5VW7wzzI5UotveSvjf/eSPtM72Yb3ou34SHjIM5H21eMiy6momnajIJphrYpdTV4Yeb4Y6Bct0ADBuAPmKmbMWAn7UCiAch4shgIWRqjbPiSWALiMFh/3kLP/JDOT2Tp7qBSndpXnWbUkvcPq87Yl9H/SfglKYUwGERwjgQM+N3Sp8c4Q8hZaK57WS28ZgB1q4EJWy2qA8wgwPghzoyNZR65Ao67y0Hz45N3XhVuwBEgkTUoWzxlpYStd7L2KdTh06owc4A3ardthrcM+vW1PB22E4vZxSx5v/w7ddYxOYLVDY22ydXppz4MoXwu/dA6B3n+ue9TNc6I7R0EO49jKvHfNNxs4qUAYxMgHCew0Asz9+++4W/vhvaMbxcdvUVrXjXx7u57Kv6NE4arhTaNox27DwEv2OVTCArPHwWJfRbP6Yrg76OX/yuwrxFeFT8DJLiyQDgkzT6w/ruzuK8Hh3lBLRBmVTKyIFBxG3GkdFjrspMyQR8kA6WZU1XIXWBNkjwLbgLgQzho+1Z3LJOQ2IB1o47kRWrYvm3VgTFz1eXivyg7HWEIWGU1EnkFRLPyKhHmc8Ra6RPHCciu8rBgVmQuLnZRZFcW/uwVoEq2JOGPB2edsdaw30+7o9sYe0v9Cn/CA6aXYxFiaYUz3od1b5FoZNfD15E=
    secretkey: AgBjiimfOUMXeCPd0nq3P6emqGn1t8Yp6O76wTI3RbY/lBYpSjhuoOLOTY6E77zF2DZbJTeTHU2ytG9gkZJAbLtN3keW5UiHFCUUfcxQrUwWjQtIrnLvi0SUeQTdUz/8gD4gUYGENj+5j24YoG0PSTqSAVqkcQEnv4VAVq2Zc3mKtJ5uvZ2E9vMBnt2JsPsNe2DpBWOSxV+EjDa43ErRig5/FWelkOqNijvwr5RWMmot6vXiOJBsICbVDPOOwBWysdAqMlJaPLkhKBSebpYoDqxLq6kJk6HLR7qm9dvkbiHs5O6JIGrER7yOsHCPsDrmqNbWvpXXwkihtH9e3HygHC5p0XImLbdSYSQ4+5RGpbHyH0hFAbuUz2UDQ+V2Oj/2YQVDuMFuTcUeEMXw1Tq3XhrIWSdsGMPxz5l98BOBs7ZXkVNgcQAofQjnTiU4eEVJ2bVvEPk0v5lEa4PFhF0suKkv5ttwsABvfAdTFmbrqX4z5YRB5Q7XMD9W61Hd5pV99mAvYWx5Q85evOwKayCBim7vnVdE1mPTt3Ij3U2xzbINrggVnbt6pv6E8Dk10gmxpOk3k4x3Tnjn94AuhuooCnDQz/BLvgnnAUIW+2fnWXbroclSkSIXBAPoXKapAb9XeUc2BUhrYXeT67FeKbM9vw/Xgi2a9qKpHeA/v4InDIdTeYCwmyAK3LzkcWYBEAfF+pVxjgNmHZbb4nU=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
