---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgCiFmqg1wzGSSLY4FSx6l/HHhEVn0/BVU+a9TGjc4XLLRpvkbRL2yHtL9ZAFjGjQ9cbBmkm/xzwAVrlLhG7OrbqHfNRcolPCT0ao3SAovWQkudzVrbKeusyXh5cDlp5rT397zYTEapOXRqUD7HFaE9UxtVERsAR9Rv2wzr81nJOGCNz4rOHLIM1wrtqMgIbYa0KKbPCSw++w0Jp3rMdRRlFUzymerxUyMXhkY+jsQyPZ+P2MmGU2gbzvv6h6KlDkMCQ9CQRb6kIH3RgyBtv+Z0Zye/N4Zm85hrB01XDskMoB1rgDZZ+yuG58bjPl7TvcGgwICzWG2EnEHzgZqRPeUUGOqLjnrIT3WTtr52WWDDevHV8YF/tAhElCHeHqMf1ct1Q4WLwMHidnCSyrVwZ0TtlOIulHPUPEPKynY7cdhLRHsExfoErjpT8ESJPwGvDLGsjneOb0V/4ocPXtbkRQMDZUG3i1ZG87mBeqj97QKl+fVNRpyN+tNuhv1JDV2b7W//IPVteIB2T06hvcPSYt7rJnIPUPDiYvZyqy/9bNYE3YCoVHzkT0cXu65haCID8PiG8CrIIT47HpyQSiYe+fCQmyl4mR4CBPGSxX6LUZ/rNYn3rHZnmYGimJG4hW7bFABXt7vpPJbLVfTr4yiZ8EM2j5kELuvmwDI7TovjDTDYyOLi7Kv8RLFS7RJnHKBb8qIDDKuKQx+0UJqg=
    secretkey: AgCvWxGIWDG8xnZq0fXw8h5/5TMEJ4/gkoHaieogZBbZKyUA12j+LIEfSFbJWzdDL1GL7Bcz7z38+ay5COoDLogDRRZUo5kNozRI+jvWAGo83cqIjlyVbSwWK0bT2s2fsh6i6UjrV9DQWOCBcHSeKjdvD8Zdto43d+ByAMWvMPcaM59CF2pnABSSeHd3WL3kaWuGO8nLevNDx1vBWpnXSwPK4kxc0LJ5jwnSl618f22w34Co6VS08HfCItasptL+JOSz96orPoVqaFf32VlVQJzIgye4IWH7j+JfKWgBrm8uiydi/+pdGfgyIZfZrN/msEUmLQUBP7DTG8hdFbJtlaV5UKPLFQF9GwO3Vd6dgfvE1bWo8uymNNFO4KVs64t6wdwzLiFHVzCu5GOjDKE6BoN2p5vL1vCNpbHsLnz8itNHO9gRYA71G+eYElrxpqXod+iG1d3eby+OGtZQ0mWo91IuKn+JLuj+I2SJD2ygiklTp0x3UtNMeyVOvA8wQsWrYy0digymm/jHV4hiU6cC31/pC61ysayOFheppvC46yU42Md/Y64FcsHNUQa+RekeKGq2+oG3i8Vnzqmhlerv5bC+CxOjoV+/SYwvZlEY/jeaPU4kEn6xj+ozOd5HieAtAX8JOKGYZym6xkFbp3LBNIQe8m9CwjT4Q+UKT14cBG9711JWIZM2yhCOYcMlbXurp3galXWbA+dbSX4=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
