---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgALnfZKeHQRbB1y21ZLQxi7+Ri2tHgLO93llqSwJv3YJBiPAX7KaZnIeUB88xmiKKJx+JU54dWhcdt10FLeTSoEEi4p6bQOpBBo/tkxT0W3n50rHK3G6/tf0FRLFAWQqWywggstBnguLGmcOLsvszAYhcNBRhRHZFetdW+XY+OfIrR21+oe6qY5+TZSzmumI6eJzQsLwTlNGwG93BNqu9Rp7graiPx4rwsfiN9g4Z85GwXigpL75WpthpBjjP2+MqR1DTzXQtGZVaV6RBU0nZ4NhtXrIvRxhI2PPVRX/YEpQPjdKMGnhEUrUazNtrtqyUnTq/JhVzB1KWW4QvgUcp6AtQWpbtFd2DnY1Lftq9QTeMfjAxblW883qCMUFtUVXE63sQXYHnTp2StQ8mYx7a/dh5L0Di7w45kuK3BSchy6WdRWoq5jfos96vJcpI0Hrt6yKUn5fVWx3bI65F6DQpQ7hmtKI4/4lDfVFSrez66sSQQYpmRqOcpiI5Tbne3cwR6W687Vwb+Kl0IX3yUeOalMDwHNiLxcikHM01I3WChodU9DsO7Xr94KayHSPG7hmfbVaXxs8TtMgv48yFXt9NJsJmgU56iQS19IVVF4rrD5Ly+CkBsFSHPZq1VRV+Dy25sXtKXw07l6IutK7LbH/2vdWeL8Lsv+izjeCYwHCFfUW8Z4dlF/z/8Z3fNjuSINQmSf/QSBdc3HHWw=
    secretkey: AgCXBhcmvPJ0d4CT3ZA7j40AMIZDLqFaxkb+ZUZdVCHhJfdJUYuuJYgH8UA6DbwI83rDKb25ngM5Ki4fKcqDr+lWiwp55LmeGW6+/beexr22qaYXfAUi8K6hOIx6iUxf2AYW+sBCGPUUm+AmwUIgNKWC7yM+lzCJFatkG7YUtunumt10oa7UPGsg3hWSkaKefgkNa5PQAWJaFwFOjZoe/y8WJj6GtB9SEuKtgUCvKNH8XR4TCSvA9XtGudu7fO/B89Abhd0BNh4HBTdxIpH3I55q9QErJC3/LMOU9iRDE/kCnUCcnpKCOorHBxc+/aTq3LcSv9wDOeAQIKPsUA/9krx704q3CvA4XD8A5LCXWal5m0/9cvffHu6AxgC8VnpwAEScaFCIc6JyQHfDeAVzlrU6MS1Jl9b6FzvRdYl21l/uHeY5sKGQ11a0Ivo2ITf86I1qza+FCOn2vioCsPx5pqbBhMeVFwzCeWmIxfJCoTNOExkVZFEAFWiVLE8dkCfEb83xxUgwo77cO0rvc1ni4gWAw57QT31fGah18ektOc3mvfaoabA38QyiF/cPw2LjwN6ZGt2WuYaiHeO9jjVVwMCIerX6SYdUKmS1gqsQqJDxLrRumb4kQfz7A8RUseUaY9kinluDO++GS+qjTLS5KD3Etc3KqexR9tgQnWBG+u1hbNiN+4U2z2c/YZHS9bkecdRvq7+zgtDJ1ag=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
