---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgCD3d9X8FHES4JnE+oWd/aH7qrupSc04tcSv4kxWEde9RDdxn9UMRPdsIi4wrOHR1STHmhz/pU8D/icPo4iDOb/mCN4FXY/l1gmk1LuiVGrDogsHaPH87KpHb+Zo9cATWWpZIPuoJY7uaN9vZzvf/fwPGVnNtLfWIy2nngBrGH/8Yxgwb3Z3cvKu9I4wcAunhPfi/zyHpTGaYVdCwf0PIDgPNrMC1L19GVX+juy78tvFsf5qunNSX+E0RqMuTdhqJ9UvCRl0xOOJJHDikjzsD9mZ/WUavvKk6rZfci4UE9mBKJNEqRTdNGnvBXEBGdS46EOdlOttMFHc9BmLI/NTvB4EIUdMmfWJ8ElnP5XTaaZ1FUKf9+uJLKaFf27gFdaUznkY6D9JNf7imDiMjDRJA1NJts3oeJ+vFenx6M6xV4H1u/v5MRdaNDVR1x+z0uhPKwuPLI1bQhlXW5WmLS/jDDMZNcAawPm+sEc6EGXMkIFdkmfJfryu51CMh4Hd2h8DLq4cBM6Eq8TxSV47yJ4wlBRTZnOF4W3Xoeu7yd4e/7WAWkNfgGpawaanLSlIbs6PfNf2JS1hTG6MRpEPWX4Ziur6Q+09wyJOmXJRBsEG9RDP8m7NqA4BoS4q+mfR0+23jTXBFrLCS74E5GFQpCDLNnggOSsMJ9xmFagBL2vE1L3ptluKVzex9WDRIuv4TKsFAlGYHLFkDsV+EciV2GLADCyM5E=
    client-secret: AgAYHF7UYAp6f3x3kM3NPRDYlh2+klioIowYeeQZJZMQ3RmEuH6tDMW1VupwamJ0N88G9RMWmrVAD7Sf25EJmgPZcvwGyipdVM6MvF2UFSy0zXhmBhM7R+gSMUqtpE/mNRsMn9i47OPWhMszwZOBa1f3se1KOqamlXC4Bf1d+ElQcFZW+H+YhqeOmjUTvf0CfAXFTK9qCqPiU22CRemMayd2aEZQOugei55uDoNGJDCH9FBMDoyL12aX0jWISF4myhoaG0M7t6R6FKUR3y67nAsQcJwfX4Zgm08kMXHuyZAzwrse6Zj9uIvZYnsPmNIsLAKpHUX4e0Wprp9qZtKOi6sn0kYvGOfnj83J/vAG/iJ94gMEcyVaNib3GFeCGRrtsQWSIkRZi1bUkAKyvWk55lBPHN2WFw/jq7BMFBEBZpXdAPfCeJRMwl98xamSIDJu+/XnZtUxTRNrh+bk7rcF+MmCSpqw1ixI5RlUeXTCn73lEVM1keT2LFFBSTfEnTzyeyhlNLguYrZJMXLXvjagea7vpzjZsycGD4r8Zk3qz9r3pMWbCPQamuYUig4L1xSRvI/VxKaQTxlXW+/i5j3CF1BtG1ugWjS5xlRxTOVmJrocJGjYhBketEZlh1gNhIQpaR5FV51WoNj92kw5Z4CdlF0+vQ80tc/QRfyCUjAKzaZ6oTWHaiQ8qOHURU/wPJrPSb7/fW+54bmnfRkyfJp35ATDGBbfip8SgoE=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
