apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: redis-password
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-dt-dev-pc-001
  target:
    name: redis-password
    creationPolicy: Owner
  data:
  - secretKey: redis_password
    remoteRef:
      key: redis-password

