---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAi5WfPZRYLj2zHi48/Wvimyz82bTEFw7/11pF7YZR0l+VBPR7CZEvEGQEK4zAl8ZLfuiJANpjjqDsnx+1dUE7fKy8XNxN97onZMT9Ksfoc6oe6P3AMkwj1WcpX690mmELBbSSOy1t8R98JShP1kWC2rNWPKt2H1Bs62fyDlYiJKIwC0oRJc47Xp4IIg5aRhvb22WcT/yUk1oop5dGpTYipnVL+Uvj/GNz1826eD8Esu5NMZX5vSc8Om5fUA5aNX99HidWnRuL6i4mOB/sM7t76NVmgDVR4Mm9U5/KUkCySMtj6QLYXaoCusMZf6uLcAn4PtePIsyoFo1GDaCgx5Z6MrXApB4WmyqXLedOxUTqU1d9/UG8i/fTStCEyVwUK4lqmJIG6XmRVjDkQcfjNISpka9vDg8j9HDhCJ46KFoYfxgQ2uv6hZB7fK7acLB2+jBuE9Y67xBBb2mQyivabGrTplxj8h++T4vAo6sY9qLdrs1N0QF5GgsSJxHesNlpJL5+fJu3K/6dq4d0mKQO+V7iuZH7eXfX1ziMjLQ2iLC2dDuYFTAhrci7H60AFXDPG0M6pNoiyTEKav9y/096HcS29zT+vslfrwsrGxKfligJllzikY2alyK1jItu8sDFvTao2icF5SaUyhWCeJ+IbrteHIxPmLltp0vNmeL/EKJKDjkrJnC8AAmCJVf60f8rwp2Opg6+pJq1v8bTKoGHiwb7ZsZ01cSAaXQlu2oXpLdhnfC7UIcYLMcj0p0D8MFVf/B4BIZnGh3VxWf/8/+dV995DIIXuTkqr1pXvY7qTBFWz52Jj2oAVOtY1VoNWR+Ww6jrk7jDJoRmhDCA7tSg0mb/3zjf2q8AwrhmhGT9ISxn0Hg5GfohQqR3ma1vP6EYb6Gf+iRvuR7qCaR8XG0NAX9fArg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
