---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgB8xTdoOEAqS3N/gbztpdEODGDoinHhuM5hz9m2QMxOIBOL8Dud+R4k1iaqQI0Arhz40SaOiW8NyWp98rs6fZRJVDQsh0Womm5jWbQlV7zsod+BB3Ohvq1Q2Zx9mnGMlvwAZs2grY8sUfWySLCpAliCyzoRHW1Tva4rJBExW+3NZQDLAM/nWnKj6hOYoX5/m7JE7Cc3x8VrbWtTK763sepPqs/b20RuJKCR+feNyYI5MltPLFEfQXh+jmShhLksSw8NvnvduVKwEIi5irrP+NlMdMDusWOBQy+59Py9Mq/CQe0u31nALvg1UIEG3KH90/MhgS+GPQpvWeElw/MKiLL1EQBOFHlJlMTXcKoCz4pooAxt+CbiWHlTI4p6CiZcUVub2eX7eqnFwKyT6HOQnJm8y7qWd3erRv3tP8YPNbKmGYtBuVKxBkB9pjH1OIPpXjYzL9Mx6M6S1lpCOVOec7EHHtrrkBfk4MRXXS+pJd2uQhvUorSo2+THyUko/m+xM9erNyJSSVTO0XSpbktmoJ120Ca2U8x6Lpjz2QxcYJPPZ3IVYgzB0Z/14LiBa5kNgla5bIwPBUJbPsPBD+tP1hbclaZ7Fkso0GgXLTH5JdaZCzQbI1wy4qcKODg3jt2c+3n403Wp4QAptsW7E+lmRTdHONQ/m2EFh9qF4cDmtsTj2LS8lspY0dYOZEY1kXeNC24=
    email: AgCuoh8A68SDsWFqb9XDwgXhx0IfAyDuJgotoXTAsIuFZGn9Yw8YK3ZU8jG+dN4gGBAQY4ZI3Q5ah3Sx6SLTrqDPTUu3wxQL+5DN6duDeLgn3oj5KdprI+hkMMxKQdOmbyk2vE4ME9nusEQ2SIqAX7zXq8EVTM6qyg7WBYkbX6KqtoyT+hyw9UFVMeuD8odHsRrk0kKTvqhK81QSiIakmdX3pCETrYKjH32MV5UxZUItakqjZ1mm+zWhIAzFHhTyS+R5OaiT4z3h88pyAP+/MOO1lCliy2YtVhIIhwRu0ubf/eLkdoPbNTftIUL2CoQykjsIM9hATigQ3DPTkQtyYu9NLRLrlwudWmt5RVPfJsQkRKwRY00lc8PD7jbDf6QNST/ooa7n4AYESyEsah5145a3drPjb6c9yGkG+lDtfFWXsLPN0b4GCb3y6G4zk7aKI7kPX/LTRhuzJ/UMvdqY0Iq53qg5IkElceCjT3o2EuWlGk3oAhmewMLie+8bWjW5hYEKwLynYm9FMtr95CW2Xm0ZKudrEZwC1ZvVfixIOc2L8h6j+GEZjQDvKvlWU6aFJsuPP+8YFlfYK/1BBK2bvGTmFYReEoLK69DwmYvMNPbbpVK+z3G0UJfAqzj9IGYMO9vNPAIX+OMl39eWIwgxrWKioS344CQS/J2JxyxVGst7vjltAbR6qvNXq/O6HHP/FvA=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
