---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCt6J0g7+X1Bx26kHBgijI5zW3tvKrPasYjTElGptwIumcaCdFo2ajXnzKWcTHW+bre+EcrwtjodrKzF72ISpN2pLvmbzxXAcbNJsQjY+x5Tz6+xbO7szPBAsVFmoB8M1rPWv5IajP7ENUJIQbp3n0pdM/4eJWDTEXmV3ZlpX9g4aNS/mF8g5IriPlZozVGiISKP4UXp9nPxCYwSlA3UyNRsjCkV9dSJ8gqn/U+o9s7F6ZxBtk5KZFKvfIE7iMRKP/x8YKVv1+lB3UgGPb2vgAe7u+7st413Z69Dzb/RzlGjDQ4Qn4+OuXN7HiQ/z5jT2CyS5WNkJVhgkLIzuu2ODsd954IbDvKlzrzrBiBkYoG/rKSHPWElue0hVJs8GIHIZILtm9Mn+pHlfDixw7NGO5QbjTHMPZwjCAoovXaaqYpEkRRPb2IjT3jC+SePXReOFQLwqzGUpNKUmwWDr4/ur+am/4b540pZDf2q2VlxP+okw3AUqz8YsKWQ6/US38h6474JXhPbrhkagyCfVzV7OX1F97xGhqFgokuZGblqJoLf//1MQnrutzJbfnAGhVZCGSCvycpxUnQAZdBJnHsX8Be3id+1aPiqf0DKYp3NPWc3MsrAIIsFVDzWSCkySFQNUxboqJtIUJ95JGbKvqCDPZvdoPiSo4SYIVaEHXfLxjWxuW4FP+B80IBi44/YIrvpsxZ0yLzeKrfUcANHIjgSd841e4O929aRTxyXSrLhpB5gXalbkBMrWSMTsza8MsCHUbnc2VTOh+YSnIUzWSJYcsc8x1P+YFtNnaQiiWG74qktx+TX15YIQvCc8X3zNVEpE4ELsDUk5apfzP4U7SbLqawT3jgoDhx1i413l+LKalPEtbaFOwsmAQyZGSkRCHX6seKBpj0o8ONhWO76KmQT1EvTg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
