nameOverride: "grafana-promtail"
fullnameOverride: "grafana-promtail"
serviceMonitor:
  enabled: true
extraArgs:
  - '-config.expand-env=true'
  - '-client.external-labels=cluster=dev'
extraEnv:
  - name: LOKI_USERNAME
    valueFrom:
      secretKeyRef:
        name: promtail-credentials
        key: username
  - name: LOKI_PASSWORD
    valueFrom:
      secretKeyRef:
        name: promtail-credentials
        key: password
config:
  clients:
    - url: http://grafana-loki-gateway.loki.svc.cluster.local/loki/api/v1/push
      tenant_id: dev
      basic_auth:
        password: ${LOKI_PASSWORD}
        username: ${LOKI_USERNAME}
  snippets:
    pipelineStages:
      - cri: {}
      - match:
          selector: '{app="plants"}'
          stages:
          - regex:
              expression: ".*(?P<trace>otelTraceID\"\\S)\\s\"(?P<traceID>[a-zA-Z\\d]+).*"
              traceID: traceID
          - labels:
              traceID:
    common:
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - namespace
          - app
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        regex: true/(.*)
        separator: /
        source_labels:
          - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
          - __meta_kubernetes_pod_container_name
        target_label: __path__
